apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproject
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudproject
  template:
    metadata:
      labels:
        app: cloudproject
    spec:
      containers:
        - name: cloudproject
          image: bkdockerefrei/node-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
